# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
   config.vm.define "web" do |web|
      config.vm.box = "generic/ubuntu1804"

      config.vm.provider "virtualbox" do |vb|
         vb.memory = "1024"
      end
      config.vm.network "forwarded_port", guest: 80, host: 8080
      config.vm.network "forwarded_port", guest: 3306, host: 8081
      web.vm.provision "shell", path: "bootstrap.sh"
      
         


         
      end
   end